globals:
  seed: 42
  device: cuda
  num_epochs: 100
  output_dir: ../output/
  main_metric: epoch_f1
  minimize_metric: False
  input_key: image
  input_target_key: targets
  model_name: ResNet
  weights:
  folds:
    - 0
  debug: True


data:
  use_train_data:
   - tp
   #  - fp 
  train_tp_df_path: input/resample-train-tp/train_tp.csv
  train_tp_audio_path: input/resample-train-tp/
  train_fp_df_path: input/resample-train-fp/train_fp.csv
  train_fp_audio_path: input/resample-train-fp/
  sub_df_path: input/birdsong-recognition/sample_submission.csv
  test_audio_path: input/resample-test/

dataset:
  name: SpectrogramDataset
  img_size: 224
  data_dir: ../input/train/
  params:
    n_mels: 128
    fmin: 20
    fmax: 16000

loss:
  name: BCELoss
  params:

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10

split:
  name: StratifiedKFold
  params:
    n_splits: 5
    random_state: 42
    shuffle: True

model:
  name: resnet50
  pretrained: True
  num_classes: 24

loader:
  train:
    batch_size: 100
    shuffle: True
    num_workers: 12
  valid:
    batch_size: 256
    shuffle: False
    num_workers: 12