globals:
  seed: 42
  device: cuda
  max_epochs: 30
  output_dir: output
  timestamp: None
  only_pred: False
  folds:
    - 0
    - 1
    - 2
    - 3
    - 4
  debug: False
  kaggle: False

mlflow:
    experiment_name: rainforest
    tags:
      timestamp: None
      model_name: None
      loss_name: None
      hash_value: None
      message: SED with mixup

data:
  root: ./
  use_train_data:
    - tp
   #  - fp 
  train_tp_df_path: input/rfcx-species-audio-detection/train_tp.csv
  train_fp_df_path: input/rfcx-species-audio-detection/train_fp.csv
  train_audio_path: input/rfcx-species-audio-detection/train
  test_audio_path: input/rfcx-species-audio-detection/test
  sub_df_path: input/rfcx-species-audio-detection/sample_submission.csv


dataset:
  name: SpectrogramDataset
  height: 224
  width: 400
  period: 10
  shift_time: 10
  strong_label_prob: 1.0
  params:
    melspec:
      n_fft: 2048
      n_mels: 128
      fmin: 80
      fmax: 15000
      power: 2.0
    pcen:
      gain: 0.98
      bias: 2
      power: 0.5
      time_constant: 0.4
      eps: 0.000001

loss:
  name: ImprovedPANNsLoss
  num_classes: 24
  params:
    output_key: clipwise_output
    weights:
      - 1.0
      - 0.5

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10

split:
  name: StratifiedKFold
  params:
    n_splits: 5
    random_state: 42
    shuffle: True

model:
  name: EfficientNetSED
  output_key: logit
  params:
    base_model_name: efficientnet-b2
    pretrained: True
    num_classes: 24

loader:
  train:
    batch_size: 20
    shuffle: True
    num_workers: 10
  valid:
    batch_size: 20
    shuffle: False
    num_workers: 10
  test:
    batch_size: 20
    shuffle: False
    num_workers: 10

transforms:
  train:

  valid:

  test:

mixup:
  flag: False
  alpha: 0.2
  prob: 0.5