globals:
  seed: 42
  device: cuda
  num_epochs: 1
  output_dir: output
  minimize_metric: False
  model_name: ResNet
  output_type: multilabel_proba
  weights:
  folds:
    - 0
  debug: True
  kaggle: False

mlflow:
    experiment_name: rainforest
    tracking_uri: mlruns
  
data:
  root: ./
  use_train_data:
    - tp
   #  - fp 
  train_df_path: input/rainforest-resample-data/resample-train/train.csv
  train_audio_path: input/rainforest-resample-data/resample-train/
  train_tp_df_path: input/rainforest-resample-data/resample-train-tp/train_tp.csv
  train_tp_audio_path: input/rainforest-resample-data/resample-train-tp/
  train_fp_df_path: input/rainforest-resample-data/resample-train-fp/train_fp.csv
  train_fp_audio_path: input/rainforest-resample-data/resample-train-fp/
  test_audio_path: input/rainforest-resample-data/resample-test/
  sub_df_path: input/rfcx-species-audio-detection/sample_submission.csv

dataset:
  name: SpectrogramDataset
  img_size: 224
  params:
    n_mels: 128
    fmin: 20
    fmax: 16000

loss:
  name: BCELoss
  params:

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10

split:
  name: StratifiedKFold
  params:
    n_splits: 5
    random_state: 42
    shuffle: True

model:
  name: resnet50
  pretrained: True
  num_classes: 24

loader:
  train:
    batch_size: 32
    shuffle: True
    num_workers: 4
  valid:
    batch_size: 50
    shuffle: False
    num_workers: 4
  test:
    batch_size: 40
    shuffle: False
    num_workers: 4