globals:
  seed: 42
  device: cuda
  num_epochs: 100
  output_dir: output
  minimize_metric: False
  model_name: ResNest
  output_type: ligits
  weights:
  folds:
    - 0
  debug: True
  kaggle: False

mlflow:
    experiment_name: rainforest
    tags:
      timestamp: None
    # tracking_uri: mlruns
  
data:
  root: ../
  use_train_data:
    - tp
   #  - fp 
  train_df_path: input/rainforest-resample-data/resample-train/train.csv
  train_audio_path: input/rainforest-resample-data/resample-train/
  test_audio_path: input/rainforest-resample-data/resample-test/
  sub_df_path: input/rfcx-species-audio-detection/sample_submission.csv


dataset:
  name: SpectrogramDataset
  img_size: 224
  params:
    n_mels: 128
    fmin: 20
    fmax: 16000

loss:
  name: BCEWithLogitsLoss
  num_classes: 24
  params:
    pos_weight: None

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10

split:
  name: StratifiedKFold
  params:
    n_splits: 5
    random_state: 42
    shuffle: True

model:
  name: ResNeSt50
  params:
    pretrained: True
    num_classes: 24

loader:
  train:
    batch_size: 32
    shuffle: True
    num_workers: 1
  valid:
    batch_size: 50
    shuffle: False
    num_workers: 1
  test:
    batch_size: 40
    shuffle: False
    num_workers: 1