globals:
  seed: 42
  device: cpu
  num_epochs: 80
  output_dir: output
  minimize_metric: False
  weights:
  folds:
    - 0
  debug: False
  kaggle: False

mlflow:
    experiment_name: rainforest
    tags:
      config_filename: None
      timestamp: None
      model_name: None
      loss_name: None
      hash_value: None
      message: 画像サイズを*1.5/fmaxを下げる
  
data:
  root: ./
  use_train_data:
    - tp
   #  - fp 
  train_tp_df_path: input/rfcx-species-audio-detection/train_tp.csv
  train_fp_df_path: input/rfcx-species-audio-detection/train_fp.csv
  train_audio_path: input/rfcx-species-audio-detection/train
  test_audio_path: input/rfcx-species-audio-detection/test
  sub_df_path: input/rfcx-species-audio-detection/sample_submission.csv


dataset:
  name: SpectrogramDataset
  height: 336
  width: 600
  shift_time: 5 
  params:
    n_mels: 128
    fmin: 80
    fmax: 15000
    power: 1.5

loss:
  name: BCEWithLogitsLoss
  num_classes: 24
  params:
    pos_weight: None

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10

split:
  name: StratifiedKFold
  params:
    n_splits: 5
    random_state: 42
    shuffle: True

model:
  name: ResNeSt50
  params:
    pretrained: True
    num_classes: 24

loader:
  train:
    batch_size: 3
    shuffle: True
    num_workers: 0
  valid:
    batch_size: 2
    shuffle: False
    num_workers: 0
  test:
    batch_size: 2
    shuffle: False
    num_workers: 0