globals:
  seed: 42
  device: cuda
  num_epochs: 100
  output_dir: ../output/
  main_metric: epoch_f1
  minimize_metric: False
  input_key: image
  input_target_key: targets
  model_name: ResNet
  weights:
  folds:
    - 0
  debug: False
  kaggle: True

mlflow:
    experiment_name: rainforest
    tracking_uri: file:/
    tags: 
      - ResNet
      - baseline
  
data:
  # root: ../input/rfcx-species-audio-detection/
  # resample_root: ../input/rainforest-resample-data/
  root: ./input/
  resample_root: ./input/
  use_train_data:
    - tp
   #  - fp 
  train_tp_df_path: resample-train-tp/train_tp.csv
  train_tp_audio_path: resample-train-tp/
  train_fp_df_path: resample-train-fp/train_fp.csv
  train_fp_audio_path: resample-train-fp/
  test_audio_path: resample-test/
  sub_df_path: sample_submission.csv

dataset:
  name: SpectrogramDataset
  img_size: 224
  data_dir: ../input/train/
  params:
    n_mels: 128
    fmin: 20
    fmax: 16000

loss:
  name: BCELoss
  params:

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10

split:
  name: StratifiedKFold
  params:
    n_splits: 5
    random_state: 42
    shuffle: True

model:
  name: resnet50
  pretrained: True
  num_classes: 24

loader:
  train:
    batch_size: 100
    shuffle: True
    num_workers: 12
  valid:
    batch_size: 256
    shuffle: False
    num_workers: 12
