globals:
  seed: 42
  device: cuda
  num_epochs: 100
  output_dir: output
  minimize_metric: False
  model_name: ResNet
  weights:
  folds:
    - 0
  debug: True
  kaggle: False

mlflow:
    experiment_name: rainforest
    tracking_uri: file:./mlflow
  
data:
  root: ./input/rfcx-species-audio-detection/
  resample_root: ./input/rainforest-resample-data/
  use_train_data:
    - tp
   #  - fp 
  train_df_path: resample-train/train.csv
  train_audio_path: resample-train/
  train_tp_df_path: resample-train-tp/train_tp.csv
  train_tp_audio_path: resample-train-tp/
  train_fp_df_path: resample-train-fp/train_fp.csv
  train_fp_audio_path: resample-train-fp/
  test_audio_path: resample-test/
  sub_df_path: sample_submission.csv

dataset:
  name: SpectrogramDataset
  img_size: 224
  params:
    n_mels: 128
    fmin: 20
    fmax: 16000

loss:
  name: BCELoss
  type: multiclass_proba
  params:

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10

split:
  name: StratifiedKFold
  params:
    n_splits: 5
    random_state: 42
    shuffle: True

model:
  name: resnet50
  pretrained: True
  num_classes: 24

loader:
  train:
    batch_size: 3
    shuffle: True
    num_workers: 4
  valid:
    batch_size: 3
    shuffle: False
    num_workers: 4
